apiVersion: apps/v1
kind: Deployment
metadata:
  name: datatjej
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: datatjej
        image: datatjej:2.2
        imagePullPolicy: Never
        ports:
        - containerPort: 80
