apiVersion: apps/v1
kind: Deployment
metadata:
  name: datatjej
  labels:
    app: datatjej
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datatjej
  template:
    metadata:
      labels:
        app: datatjej
    spec:
      containers:
      - name: datatjej
        image: datatjej:2.0
        imagePullPolicy: Never
        ports:
        - containerPort: 80
